vpc_cidr_block      = "10.0.0.0/16"
subnet_cidr_block   = "10.0.10.0/24"
avail_zone          = "us-west-2a"
env_prefix          = "dev"
instance_type       = "t2.micro"
ami_name = "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"
key_pair = "jenkins-server"